
[General]
# If SendErrors is `true`, the server will send helpful info about crashes and other issues back to the BeamMP developers. This info may include your config, who is on your server at the time of the error, and similar general information. This kind of data is vital in helping us diagnose and fix issues faster. This has no impact on server performance. You can opt-out of this system by setting this to `false`
SendErrorsShowMessage = false

Name = "Connect Hosting Free server"
Port = 
ResourceFolder = "Resources"
# Change the Auth Key in the startup section above settings on the connect hosting panel.
AuthKey = ""
Private = false
# Change the Playey count in the startup section above settings on the connect hosting panel.
MaxPlayers = 10
Debug = false
Description = "Connect Hosting Free server, join the discord https://discord.gg/Dz3zTMSeuy"
MaxCars = 5
Map = "/levels/west_coast_usa/info.json"
# You can turn on/off the SendErrors message you get on startup here
SendErrors = true

[HTTP]
SSLCertPath = "./.ssl/HttpServer/cert.pem"
HTTPServerPort = 8080
# Recommended to keep enabled. With SSL the server will serve https and requires valid key and cert files
UseSSL = false
SSLKeyPath = "./.ssl/HttpServer/key.pem"
# Enables the internal HTTP server
HTTPServerEnabled = false


[Misc]
# If SendErrors is `true`, the server will send helpful info about crashes and other issues back to the BeamMP developers. This info may include your config, who is on your server at the time of the error, and similar general information. This kind of data is vital in helping us diagnose and fix issues faster. This has no impact on server performance. You can opt-out of this system by setting this to `false`
SendErrorsShowMessage = true
# Hides the periodic update message which notifies you of a new server version. You should really keep this on and always update as soon as possible. For more information visit https://wiki.beammp.com/en/home/server-maintenance#updating-the-server. An update message will always appear at startup regardless.
ImScaredOfUpdates = true
# You can turn on/off the SendErrors message you get on startup here
SendErrors = true
